name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
